// src/app/api/inngest/route.ts
import { serve } from "inngest/next";
import { inngest } from "../../../inngest/client";
import {
  accountDelete,
  accountDeletionSweep,
  accountExport,
  analyticsBackfill,
  analyticsCron,
  auditExport,
  autoSummarizeThread,
  backfillIntegration,
  billingSeatsSync,
  channelCallbackReceived,
  channelMessageReceived,
  clerkMembershipSync,
  clerkOrgSync,
  corsairWebhookReceived,
  firefliesTranscriptReady,
  followUpReminders,
  gmailWatchOnConnect,
  gmailWatchRenew,
  memberOffboarding,
  processTask,
  retentionPurge,
  retentionPurgeCron,
  ruleSuggestionsCron,
  scheduledSend,
  scoreInboxBackfill,
  searchEmbeddingsBackfill,
  snoozeWake,
  summarizeBackfill,
  dodoWebhookReceived,
  styleBackfill,
  styleIngestSent,
  styleProfileRegenerate,
} from "../../../inngest/functions";

export const { GET, POST, PUT } = serve({
  client: inngest,
  functions: [
    processTask,
    backfillIntegration,
    corsairWebhookReceived,
    autoSummarizeThread,
    summarizeBackfill,
    firefliesTranscriptReady,
    gmailWatchOnConnect,
    gmailWatchRenew,
    scoreInboxBackfill,
    searchEmbeddingsBackfill,
    channelMessageReceived,
    channelCallbackReceived,
    snoozeWake,
    scheduledSend,
    followUpReminders,
    styleIngestSent,
    styleBackfill,
    styleProfileRegenerate,
    ruleSuggestionsCron,
    clerkOrgSync,
    clerkMembershipSync,
    dodoWebhookReceived,
    billingSeatsSync,
    memberOffboarding,
    retentionPurgeCron,
    retentionPurge,
    analyticsCron,
    analyticsBackfill,
    accountExport,
    accountDeletionSweep,
    accountDelete,
    auditExport,
  ],
});
